import './global.css';

import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/ui/themes';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Welcome to ghost-ai',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`dark ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <ClerkProvider
          appearance={{
            theme: dark,
            variables: {
              colorBackground: 'hsl(var(--background))',
              colorForeground: 'hsl(var(--foreground))',
              colorPrimary: 'hsl(var(--primary))',
              colorPrimaryForeground: 'hsl(var(--primary-foreground))',
              colorInput: 'hsl(var(--input))',
              colorInputForeground: 'hsl(var(--foreground))',
              colorMutedForeground: 'hsl(var(--muted-foreground))',
              colorBorder: 'hsl(var(--border))',
              colorRing: 'hsl(var(--ring))',
              colorDanger: 'hsl(var(--destructive))',
              borderRadius: 'var(--radius)',
            },
          }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
