import './global.css';

import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/ui/themes';

export const metadata = {
  title: 'Welcome to ghost-ai',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <ClerkProvider
          appearance={{
            theme: dark,
            variables: {
              colorBackground: 'hsl(var(--background))',
              colorForeground: 'hsl(var(--foreground))',
              colorPrimary: 'hsl(var(--primary))',
              colorPrimaryForeground: 'hsl(var(--primary-foreground))',
              colorInput: 'hsl(var(--input))',
              colorInputForeground: 'hsl(var(--foreground))',
              colorMutedForeground: 'hsl(var(--muted-foreground))',
              colorBorder: 'hsl(var(--border))',
              colorRing: 'hsl(var(--ring))',
              colorDanger: 'hsl(var(--destructive))',
              borderRadius: 'var(--radius)',
            },
          }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
